pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        TERRAFORM_DIR = './04_IAM_S3' 
        TERRAFORM_CREDENTIALS_ID = 'AWS-Cred'
    }

    stages {
        stage('Starting execution') {
            steps {
                echo 'Pipeline has been started successfully!'
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    dir(TERRAFORM_DIR) {
                        withCredentials([aws(credentialsId: TERRAFORM_CREDENTIALS_ID, region: AWS_REGION)]) {
                            sh 'terraform destroy'
                            sh 'terraform init'
                        }
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    dir(TERRAFORM_DIR) {
                        withCredentials([aws(credentialsId: TERRAFORM_CREDENTIALS_ID, region: AWS_REGION)]) {
                            sh 'terraform apply -auto-approve'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
