pipeline{
    agent none

    stages{
        stage('Starting execution')
        {
            steps{
             echo 'Pipeline has been started succesfully!'
            }        
        }

         stage('Terraform apply')
         {
            agent any
            steps{
            sh '''
            terraform init
            terraform apply -auto-approve
            '''
            }
         }
    }
   
}