pipeline {
    agent none

    stages {
        stage('Starting execution') {
            steps {
                echo 'Pipeline has been started successfully!'
            }
        }

        stage('Terraform apply') {
            agent any
            steps {
               {
                    script {
                        withCredentials([aws(credentialsId: 'Aws-Cred', region: 'ap-south-1')])
                        {
                             dir('./04_IAM_S3') 
                             {
                            sh 'terraform init'
                            sh 'terraform apply -auto-approve'
                             }                       
                        }

                    }

                }
            }
        }
    }
}
